# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'incoming_transfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QLocale
from PyQt5.QtGui import QDoubleValidator
from datetime import date
from PyQt5.QtWidgets import QFileDialog, QMainWindow
import uuid


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        self.path = ""
        self.english = QLocale(QLocale.English, QLocale.UnitedKingdom)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(344, 289)
        self.date = date.today()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setGeometry(QtCore.QRect(210, 200, 91, 31))
        self.button_save.setObjectName("button_save")
        self.button_save.clicked.connect(self.save_file)
        self.input_date = QtWidgets.QDateEdit(self.centralwidget)
        self.input_date.setGeometry(QtCore.QRect(50, 120, 110, 22))
        self.input_date.setDate(self.date)
        self.input_date.setCalendarPopup(True)
        self.input_date.setObjectName("input_date")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(50, 50, 61, 21))
        self.input_amount.setObjectName("input_amount")
        self.input_amount.setValidator(QDoubleValidator(0.00, 999999999999.99, 2))
        self.input_amount.validator().setLocale(self.english)
        self.label_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_amount.setGeometry(QtCore.QRect(60, 30, 47, 13))
        self.label_amount.setObjectName("label_amount")
        self.select_currency = QtWidgets.QComboBox(self.centralwidget)
        self.select_currency.setGeometry(QtCore.QRect(160, 50, 69, 22))
        self.select_currency.setObjectName("select_currency")
        self.select_currency.addItem("")
        self.select_currency.addItem("")
        self.select_currency.addItem("")
        self.label_currency = QtWidgets.QLabel(self.centralwidget)
        self.label_currency.setGeometry(QtCore.QRect(170, 30, 47, 13))
        self.label_currency.setObjectName("label_currency")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(60, 90, 47, 13))
        self.label_date.setObjectName("label_date")
        self.button_choose = QtWidgets.QPushButton(self.centralwidget)
        self.button_choose.setGeometry(QtCore.QRect(50, 200, 91, 31))
        self.button_choose.setObjectName("button_choose")
        self.button_choose.clicked.connect(self.choose_directory)
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(60, 170, 47, 13))
        self.label_path.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_save.setText(_translate("MainWindow", "Save XML"))
        self.input_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_amount.setText(_translate("MainWindow", "Amount"))
        self.select_currency.setItemText(0, _translate("MainWindow", "USD"))
        self.select_currency.setItemText(1, _translate("MainWindow", "GBP"))
        self.select_currency.setItemText(2, _translate("MainWindow", "EUR"))
        self.label_currency.setText(_translate("MainWindow", "Currency"))
        self.label_date.setText(_translate("MainWindow", "Date"))
        self.button_choose.setText(_translate("MainWindow", "Choose directory"))

    def choose_directory(self):
        self.path = QFileDialog.getExistingDirectory(self, "Choose directory", "C:/",
                                                     QFileDialog.ShowDirsOnly
                                                     | QFileDialog.DontResolveSymlinks)
        if self.path != "":
            self.label_path.setText(f"File will be saved in {self.path}")
            self.label_path.adjustSize()

    def save_file(self):
        acct_svcr_ref = str(uuid.uuid4())
        amount = self.english.toDouble(self.input_amount.text())[0]
        currency = self.select_currency.currentText()
        date = self.input_date.date().toPyDate()
        if currency == "USD":
            bank_account = "52495788"
        elif currency == "GBP":
            bank_account = "43975347"
        elif currency == "EUR":
            bank_account = "52588299"
        if amount == 0.0:
            warning = QtWidgets.QMessageBox()
            warning.setWindowTitle("Attention!")
            warning.setText("Amount value is 0.00")
            warning.setIcon(QtWidgets.QMessageBox.Warning)
            warning.exec_()
        elif self.path == "":
            warning = QtWidgets.QMessageBox()
            warning.setWindowTitle("Attention!")
            warning.setText("Please choose directory")
            warning.setIcon(QtWidgets.QMessageBox.Warning)
            warning.exec_()
        else:
            file_name = f"incoming_internal_transfer_{date}_{amount}_{currency}.xml"
            file = open(f"{self.path}/{file_name}.xml", "w")
            file.write(f'<?xml version="1.0" encoding="UTF-8"?> \n'
                       f'<Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02">\n'
                       f'<BkToCstmrAcctRptV02>\n'
                       f'<GrpHdr>\n'
                       f'<MsgId>10929926</MsgId>\n'
                       f'<CreDtTm>{date} 10:51:25</CreDtTm>\n'
                       f'<MsgRcpt>\n'
                       f'<Nm>STENN INTERNATIONAL LIMITED</Nm>\n'
                       f'<PstlAdr>\n'
                       f'<AdrTp>ADDR</AdrTp>\n'
                       f'<StrtNm>DURHAM STREET</StrtNm>\n'
                       f'<BldgNb>V 101, 1-45</BldgNb>\n'
                       f'<PstCd>SE11 5JH</PstCd>\n'
                       f'<TwnNm>LONDON</TwnNm>\n'
                       f'<CtrySubDvsn>LONDON</CtrySubDvsn>\n'
                       f'<Ctry>GB</Ctry>\n'
                       f'<AdrLine>STENN INTERNATIONAL LTD</AdrLine>\n'
                       f'</PstlAdr>\n'
                       f'</MsgRcpt>\n'
                       f'<AddtlInf>INTR</AddtlInf>\n'
                       f'</GrpHdr>\n'
                       f'<Rpt>\n'
                       f'<Id>10929926</Id>\n'
                       f'<ElctrncSeqNb>016/000</ElctrncSeqNb>\n'
                       f'<CreDtTm>{date} 10:51:25</CreDtTm>\n'
                       f'<FrToDt>\n'
                       f'<FrDtTm>2017-01-09T00:00:00</FrDtTm>\n'
                       f'<ToDtTm>2017-01-23T06:32:35</ToDtTm>\n'
                       f'</FrToDt>\n'
                       f'<RptgSrc>\n'
                       f'<Cd>ACCT</Cd>\n'
                       f'</RptgSrc>\n'
                       f'<Acct>\n'
                       f'<Id>\n'
                       f'<Othr>\n'
                       f'<Id>{bank_account}</Id>\n'
                       f'<SchmeNm>\n'
                       f'<Prtry>BARCLAYS</Prtry>\n'
                       f'</SchmeNm>\n'
                       f'</Othr>\n'
                       f'</Id>\n'
                       f'<Ccy>{currency}</Ccy>\n'
                       f'<Nm>STENN ASSETS UK LTD</Nm>\n'
                       f'<Svcr>\n'
                       f'<FinInstnId>\n'
                       f'<ClrSysMmbId>\n'
                       f'<ClrSysId>\n'
                       f'<Prtry>25000</Prtry>\n'
                       f'</ClrSysId>\n'
                       f'<MmbId>Barclays</MmbId>\n'
                       f'</ClrSysMmbId>\n'
                       f'<Nm>Barclays UK Currency</Nm>\n'
                       f'</FinInstnId>\n'
                       f'</Svcr>\n'
                       f'</Acct>\n'
                       f'<Bal>\n'
                       f'<Tp>\n'
                       f'<CdOrPrtry>\n'
                       f'<Cd>ITBD</Cd>\n'
                       f'</CdOrPrtry>\n'
                       f'</Tp>\n'
                       f'<Amt Ccy="{currency}">{amount}</Amt>\n'
                       f'<CdtDbtInd>CRDT</CdtDbtInd>\n'
                       f'<Dt>\n'
                       f'<Dt>{date}</Dt>\n'
                       f'</Dt>\n'
                       f'</Bal>\n'
                       f'<TxsSummry>\n'
                       f'<TtlNtries>\n'
                       f'<NbOfNtries>1</NbOfNtries>\n'
                       f'<Sum>{amount}</Sum>\n'
                       f'<TtlNetNtryAmt>{amount}</TtlNetNtryAmt>\n'
                       f'<CdtDbtInd>CRDT</CdtDbtInd>\n'
                       f'</TtlNtries>\n'
                       f'<TtlCdtNtries>\n'
                       f'<NbOfNtries>1</NbOfNtries>\n'
                       f'<Sum>{amount}</Sum>\n'
                       f'</TtlCdtNtries>\n'
                       f'<TtlDbtNtries>\n'
                       f'<NbOfNtries>0</NbOfNtries>\n'
                       f'<Sum>0.00</Sum>\n'
                       f'</TtlDbtNtries>\n'
                       f'</TxsSummry>\n'
                       f'<Ntry>\n'
                       f'<Amt Ccy="{currency}">{amount}</Amt>\n'
                       f'<CdtDbtInd>CRDT</CdtDbtInd>\n'
                       f'<RvslInd>False</RvslInd>\n'
                       f'<Sts>BOOK</Sts>\n'
                       f'<BookgDt>\n'
                       f'<Dt>0116</Dt>\n'
                       f'</BookgDt>\n'
                       f'<ValDt>\n'
                       f'<Dt>170113</Dt>\n'
                       f'</ValDt>\n'
                       f'<AcctSvcrRef>{acct_svcr_ref}</AcctSvcrRef>\n'
                       f'<BkTxCd>\n'
                       f'<Prtry>\n'
                       f'<Cd>175</Cd>\n'
                       f'<Issr>BARCLAYS</Issr>\n'
                       f'</Prtry>\n'
                       f'</BkTxCd>\n'
                       f'<NtryDtls>\n'
                       f'<TxDtls>\n'
                       f'<Refs>\n'
                       f'<AcctSvcrRef>{acct_svcr_ref}</AcctSvcrRef>\n'
                       f'<EndToEndId>STENN ASSETS UK LTD</EndToEndId>\n'
                       f'</Refs>\n'
                       f'</TxDtls>\n'
                       f'</NtryDtls>\n'
                       f'<AddtlNtryInf>DESCRIPTION</AddtlNtryInf>\n'
                       f'</Ntry>\n'
                       f'</Rpt>\n'
                       f'</BkToCstmrAcctRptV02>\n'
                       f'</Document>\n'
                       )
            file.close()
            self.label_path.setText(f"Successfully created in {self.path}")
            self.label_path.adjustSize()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
