# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'incoming_transfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator
from datetime import date


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(344, 289)
        self.date = date.today()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setGeometry(QtCore.QRect(210, 200, 91, 31))
        self.button_save.setObjectName("button_save")
        self.button_save.clicked.connect(self.save_file)
        self.input_date = QtWidgets.QDateEdit(self.centralwidget)
        self.input_date.setGeometry(QtCore.QRect(50, 120, 110, 22))
        self.input_date.setDate(self.date)
        self.input_date.setCalendarPopup(True)
        self.input_date.setObjectName("input_date")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(50, 50, 61, 21))
        self.input_amount.setObjectName("input_amount")
        self.input_amount.setValidator(QDoubleValidator())
        self.label_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_amount.setGeometry(QtCore.QRect(60, 30, 47, 13))
        self.label_amount.setObjectName("label_amount")
        self.select_currency = QtWidgets.QComboBox(self.centralwidget)
        self.select_currency.setGeometry(QtCore.QRect(160, 50, 69, 22))
        self.select_currency.setObjectName("select_currency")
        self.select_currency.addItem("")
        self.select_currency.addItem("")
        self.select_currency.addItem("")
        self.label_currency = QtWidgets.QLabel(self.centralwidget)
        self.label_currency.setGeometry(QtCore.QRect(170, 30, 47, 13))
        self.label_currency.setObjectName("label_currency")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(60, 90, 47, 13))
        self.label_date.setObjectName("label_date")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_save.setText(_translate("MainWindow", "Save XML"))
        self.input_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_amount.setText(_translate("MainWindow", "Amount"))
        self.select_currency.setItemText(0, _translate("MainWindow", "USD"))
        self.select_currency.setItemText(1, _translate("MainWindow", "GBP"))
        self.select_currency.setItemText(2, _translate("MainWindow", "EUR"))
        self.label_currency.setText(_translate("MainWindow", "Currency"))
        self.label_date.setText(_translate("MainWindow", "Date"))

    def save_file(self):
        file = open("saved.txt", "w")
        file.write(f"{self.input_amount.text()} {self.select_currency.currentText()} on "
                   f"{self.input_date.date().toPyDate()} {self.date}")
        file.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())